// this code is autogenerated, do not check it into to your code repository

// ref lib/flash_profile/native.ex:62
const std = @import("std");
const beam = @import("beam");

// ============================================================================
// CharSet - Efficient ASCII character set using 128-bit bitmap
// ============================================================================

const CharSet = struct {
    low: u64,
    high: u64,

    fn empty() CharSet {
        return .{ .low = 0, .high = 0 };
    }

    fn fromChars(chars: []const u8) CharSet {
        var set = empty();
        for (chars) |c| {
            set.add(c);
        }
        return set;
    }

    fn add(self: *CharSet, c: u8) void {
        if (c < 64) {
            self.low |= @as(u64, 1) << @intCast(c);
        } else if (c < 128) {
            self.high |= @as(u64, 1) << @intCast(c - 64);
        }
    }

    fn contains(self: CharSet, c: u8) bool {
        if (c < 64) {
            return (self.low & (@as(u64, 1) << @intCast(c))) != 0;
        } else if (c < 128) {
            return (self.high & (@as(u64, 1) << @intCast(c - 64))) != 0;
        }
        return false;
    }
};

// ============================================================================
// Default Character Sets (from FlashProfile paper Figure 6)
// ============================================================================

const lower_chars = "abcdefghijklmnopqrstuvwxyz";
const upper_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const digit_chars = "0123456789";
const alpha_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
const alphadigit_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
const space_chars = " \t\n\r";

// Static costs from paper
const LOWER_COST: f64 = 9.1;
const UPPER_COST: f64 = 8.2;
const DIGIT_COST: f64 = 8.2;
const ALPHA_COST: f64 = 15.0;
const ALPHADIGIT_COST: f64 = 20.0;
const SPACE_COST: f64 = 5.0;
const ANY_COST: f64 = 100.0;

// ============================================================================
// Pattern Matching
// ============================================================================

/// Match a variable-width character class against a string.
/// Returns length of longest prefix with all chars in set, or 0 if no match.
fn matchCharClass(string: []const u8, char_set: CharSet) usize {
    var count: usize = 0;
    for (string) |c| {
        if (char_set.contains(c)) {
            count += 1;
        } else {
            break;
        }
    }
    return count;
}

/// Match any printable ASCII character
fn matchAny(string: []const u8) usize {
    var count: usize = 0;
    for (string) |c| {
        if (c >= 32 and c <= 126) {
            count += 1;
        } else {
            break;
        }
    }
    return count;
}

/// Match a constant string prefix
fn matchConstant(string: []const u8, constant: []const u8) usize {
    if (string.len < constant.len) return 0;
    if (std.mem.eql(u8, string[0..constant.len], constant)) {
        return constant.len;
    }
    return 0;
}

// ============================================================================
// NIF Functions
// ============================================================================

/// Match a character class against a string.
/// atom_name: "Lower", "Upper", "Digit", "Alpha", "AlphaDigit", "Space", "Any"
/// Returns: length of match (0 = no match)
pub fn match_char_class(atom_name: []const u8, string: []const u8) usize {
    if (std.mem.eql(u8, atom_name, "Lower")) {
        return matchCharClass(string, CharSet.fromChars(lower_chars));
    } else if (std.mem.eql(u8, atom_name, "Upper")) {
        return matchCharClass(string, CharSet.fromChars(upper_chars));
    } else if (std.mem.eql(u8, atom_name, "Digit")) {
        return matchCharClass(string, CharSet.fromChars(digit_chars));
    } else if (std.mem.eql(u8, atom_name, "Alpha")) {
        return matchCharClass(string, CharSet.fromChars(alpha_chars));
    } else if (std.mem.eql(u8, atom_name, "AlphaDigit")) {
        return matchCharClass(string, CharSet.fromChars(alphadigit_chars));
    } else if (std.mem.eql(u8, atom_name, "Space")) {
        return matchCharClass(string, CharSet.fromChars(space_chars));
    } else if (std.mem.eql(u8, atom_name, "Any")) {
        return matchAny(string);
    }
    return 0;
}

/// Match a constant string prefix
pub fn match_constant(constant: []const u8, string: []const u8) usize {
    return matchConstant(string, constant);
}

/// Get the static cost for a character class atom
pub fn get_static_cost(atom_name: []const u8) f64 {
    if (std.mem.eql(u8, atom_name, "Lower")) {
        return LOWER_COST;
    } else if (std.mem.eql(u8, atom_name, "Upper")) {
        return UPPER_COST;
    } else if (std.mem.eql(u8, atom_name, "Digit")) {
        return DIGIT_COST;
    } else if (std.mem.eql(u8, atom_name, "Alpha")) {
        return ALPHA_COST;
    } else if (std.mem.eql(u8, atom_name, "AlphaDigit")) {
        return ALPHADIGIT_COST;
    } else if (std.mem.eql(u8, atom_name, "Space")) {
        return SPACE_COST;
    } else if (std.mem.eql(u8, atom_name, "Any")) {
        return ANY_COST;
    }
    return 100.0; // Default high cost
}

/// Calculate dynamic weight for an atom position in a pattern.
/// W(i, S | P) = (1/|S|) * sum over s in S of (len_i(s) / |s|)
pub fn calculate_dynamic_weight(match_lengths: []const u32, string_lengths: []const u32) f64 {
    if (match_lengths.len == 0 or string_lengths.len == 0) {
        return 0.0;
    }

    var total: f64 = 0.0;
    const n = @min(match_lengths.len, string_lengths.len);

    for (0..n) |i| {
        const match_len = match_lengths[i];
        const string_len = string_lengths[i];

        if (string_len > 0) {
            const fraction = @as(f64, @floatFromInt(match_len)) / @as(f64, @floatFromInt(string_len));
            total += fraction;
        }
    }

    return total / @as(f64, @floatFromInt(n));
}

/// Check if a string consists entirely of characters from a character class
pub fn string_matches_class(atom_name: []const u8, string: []const u8) bool {
    const match_len = match_char_class(atom_name, string);
    return match_len == string.len and match_len > 0;
}
// ref lib/flash_profile/native.ex:246
const flash_nif = @import("flash_profile_nif");

// Re-export NIF functions
pub const profile_nif = flash_nif.profile_nif;
pub const big_profile_nif = flash_nif.big_profile_nif;
pub const dissimilarity_nif = flash_nif.dissimilarity_nif;
pub const learn_pattern_nif = flash_nif.learn_pattern_nif;
pub const matches_nif = flash_nif.matches_nif;
pub const calculate_cost_nif = flash_nif.calculate_cost_nif;
