defmodule FlashProfile.ProfileEntry do
  @moduledoc """
  A single entry in a FlashProfile profile.

  Each entry contains:
  - `data`: List of strings described by this pattern
  - `pattern`: The learned pattern (list of atoms)
  - `cost`: Cost of the pattern over the data

  Profile entries are generated by the profiling algorithm and can be
  compressed using the Compress module.
  """

  alias FlashProfile.Atom

  @type t :: %__MODULE__{
          data: [String.t()],
          pattern: [Atom.t()] | nil,
          cost: float() | :infinity
        }

  defstruct [:data, :pattern, :cost]

  @doc """
  Create a new ProfileEntry.

  ## Parameters

    - `data` - List of strings
    - `pattern` - List of atoms forming the pattern (or nil)
    - `cost` - Cost of the pattern (or :infinity)

  ## Examples

      iex> alias FlashProfile.ProfileEntry
      iex> entry = %ProfileEntry{data: ["ABC", "DEF"], pattern: [], cost: 5.0}
      iex> entry.data
      ["ABC", "DEF"]
  """
  def new(data, pattern, cost) do
    %__MODULE__{data: data, pattern: pattern, cost: cost}
  end
end
